### ISSUE TITLE
NameError when installing Project Connector

### ISSUE THREAD

**Issue by Rocksau80** [conveniencable/microsoft_project_connector#10]
Hello,
as soon as I install the plugin i get this error:
`uninitialized constant Patches::IssuePatch (NameError)
  /var/www/redmine/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/helpers.rb:135:in `const_get'
  /var/www/redmine/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/helpers.rb:135:in `cget'
  /var/www/redmine/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/eager_load.rb:169:in `block in actual_eager_load_dir'
  /var/www/redmine/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/helpers.rb:40:in `block in ls'
  /var/www/redmine/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/helpers.rb:25:in `each'
  /var/www/redmine/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/helpers.rb:25:in `ls'
  /var/www/redmine/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/eager_load.rb:164:in `actual_eager_load_dir'
  /var/www/redmine/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/eager_load.rb:17:in `block (2 levels) in eager_load'
  /var/www/redmine/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/eager_load.rb:16:in `each'
  /var/www/redmine/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/eager_load.rb:16:in `block in eager_load'
  /var/www/redmine/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/eager_load.rb:10:in `synchronize'
  /var/www/redmine/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/eager_load.rb:10:in `eager_load'
  /var/www/redmine/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader.rb:297:in `block in eager_load_all'
  /var/www/redmine/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader.rb:295:in `each'
  /var/www/redmine/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader.rb:295:in `eager_load_all'
  /var/www/redmine/vendor/bundle/ruby/3.0.0/gems/railties-6.1.7.2/lib/rails/application/finisher.rb:133:in `block in <module:Finisher>'
  /var/www/redmine/vendor/bundle/ruby/3.0.0/gems/railties-6.1.7.2/lib/rails/initializable.rb:32:in `instance_exec'
  /var/www/redmine/vendor/bundle/ruby/3.0.0/gems/railties-6.1.7.2/lib/rails/initializable.rb:32:in `run'
  /var/www/redmine/vendor/bundle/ruby/3.0.0/gems/railties-6.1.7.2/lib/rails/initializable.rb:61:in `block in run_initializers'
  /usr/lib/ruby/3.0.0/tsort.rb:228:in `block in tsort_each'
  /usr/lib/ruby/3.0.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
  /usr/lib/ruby/3.0.0/tsort.rb:431:in `each_strongly_connected_component_from'
  /usr/lib/ruby/3.0.0/tsort.rb:349:in `block in each_strongly_connected_component'
  /usr/lib/ruby/3.0.0/tsort.rb:347:in `each'
  /usr/lib/ruby/3.0.0/tsort.rb:347:in `call'
  /usr/lib/ruby/3.0.0/tsort.rb:347:in `each_strongly_connected_component'
  /usr/lib/ruby/3.0.0/tsort.rb:226:in `tsort_each'
  /usr/lib/ruby/3.0.0/tsort.rb:205:in `tsort_each'
  /var/www/redmine/vendor/bundle/ruby/3.0.0/gems/railties-6.1.7.2/lib/rails/initializable.rb:60:in `run_initializers'
  /var/www/redmine/vendor/bundle/ruby/3.0.0/gems/railties-6.1.7.2/lib/rails/application.rb:391:in `initialize!'
  /var/www/redmine/config/environment.rb:16:in `<top (required)>'
  config.ru:3:in `require'
  config.ru:3:in `block in <main>'
  /var/www/redmine/vendor/bundle/ruby/3.0.0/gems/rack-2.2.6.4/lib/rack/builder.rb:125:in `instance_eval'
  /var/www/redmine/vendor/bundle/ruby/3.0.0/gems/rack-2.2.6.4/lib/rack/builder.rb:125:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:101:in `eval'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:101:in `preload_app'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:189:in `block in <module:App>'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:390:in `run_block_and_record_step_progress'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:188:in `<module:App>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
  /usr/share/passenger/helper-scripts/rack-preloader.rb:29:in `<main>'
The stdout/stderr output of the subprocess so far is:

Error: The application encountered the following error: uninitialized constant Patches::IssuePatch (NameError)
    /var/www/redmine/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/helpers.rb:135:in `const_get'
    /var/www/redmine/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/helpers.rb:135:in `cget'
    /var/www/redmine/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/eager_load.rb:169:in `block in actual_eager_load_dir'
    /var/www/redmine/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/helpers.rb:40:in `block in ls'
    /var/www/redmine/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/helpers.rb:25:in `each'
    /var/www/redmine/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/helpers.rb:25:in `ls'
    /var/www/redmine/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/eager_load.rb:164:in `actual_eager_load_dir'
    /var/www/redmine/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/eager_load.rb:17:in `block (2 levels) in eager_load'
    /var/www/redmine/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/eager_load.rb:16:in `each'
    /var/www/redmine/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/eager_load.rb:16:in `block in eager_load'
    /var/www/redmine/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/eager_load.rb:10:in `synchronize'
    /var/www/redmine/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader/eager_load.rb:10:in `eager_load'
    /var/www/redmine/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader.rb:297:in `block in eager_load_all'
    /var/www/redmine/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader.rb:295:in `each'
    /var/www/redmine/vendor/bundle/ruby/3.0.0/gems/zeitwerk-2.6.7/lib/zeitwerk/loader.rb:295:in `eager_load_all'
    /var/www/redmine/vendor/bundle/ruby/3.0.0/gems/railties-6.1.7.2/lib/rails/application/finisher.rb:133:in `block in <module:Finisher>'
    /var/www/redmine/vendor/bundle/ruby/3.0.0/gems/railties-6.1.7.2/lib/rails/initializable.rb:32:in `instance_exec'
    /var/www/redmine/vendor/bundle/ruby/3.0.0/gems/railties-6.1.7.2/lib/rails/initializable.rb:32:in `run'
    /var/www/redmine/vendor/bundle/ruby/3.0.0/gems/railties-6.1.7.2/lib/rails/initializable.rb:61:in `block in run_initializers'
    /usr/lib/ruby/3.0.0/tsort.rb:228:in `block in tsort_each'
    /usr/lib/ruby/3.0.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
    /usr/lib/ruby/3.0.0/tsort.rb:431:in `each_strongly_connected_component_from'
    /usr/lib/ruby/3.0.0/tsort.rb:349:in `block in each_strongly_connected_component'
    /usr/lib/ruby/3.0.0/tsort.rb:347:in `each'
    /usr/lib/ruby/3.0.0/tsort.rb:347:in `call'
    /usr/lib/ruby/3.0.0/tsort.rb:347:in `each_strongly_connected_component'
    /usr/lib/ruby/3.0.0/tsort.rb:226:in `tsort_each'
    /usr/lib/ruby/3.0.0/tsort.rb:205:in `tsort_each'
    /var/www/redmine/vendor/bundle/ruby/3.0.0/gems/railties-6.1.7.2/lib/rails/initializable.rb:60:in `run_initializers'
    /var/www/redmine/vendor/bundle/ruby/3.0.0/gems/railties-6.1.7.2/lib/rails/application.rb:391:in `initialize!'
    /var/www/redmine/config/environment.rb:16:in `<top (required)>'
    config.ru:3:in `require'
    config.ru:3:in `block in <main>'
    /var/www/redmine/vendor/bundle/ruby/3.0.0/gems/rack-2.2.6.4/lib/rack/builder.rb:125:in `instance_eval'
    /var/www/redmine/vendor/bundle/ruby/3.0.0/gems/rack-2.2.6.4/lib/rack/builder.rb:125:in `initialize'
    config.ru:1:in `new'
    config.ru:1:in `<main>'
    /usr/share/passenger/helper-scripts/rack-preloader.rb:101:in `eval'
    /usr/share/passenger/helper-scripts/rack-preloader.rb:101:in `preload_app'
    /usr/share/passenger/helper-scripts/rack-preloader.rb:189:in `block in <module:App>'
    /usr/lib/ruby/vendor_ruby/phusion_passenger/loader_shared_helpers.rb:390:in `run_block_and_record_step_progress'
    /usr/share/passenger/helper-scripts/rack-preloader.rb:188:in `<module:App>'
    /usr/share/passenger/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
    /usr/share/passenger/helper-scripts/rack-preloader.rb:29:in `<main>'`

What am I missing?

**Comment by Rocksau80** [comment]
After a bit of research that might be related to the Rails version I'm using.
Environment:
  Redmine version                5.0.5.stable
  Ruby version                   3.0.2-p107 (2021-07-07) [x86_64-linux-gnu]
  Rails version                  6.1.7.2

**Comment by Rocksau80** [comment]
I did some more research. It might be caused by the changes introduced by the switch to zeitwerk as the new autoloader.
I tried to fixed it with the help in that description: https://zenn.dev/onozaty/articles/redmine5-plugin-migration but my ruby knowledge is too limited.

**Comment by conveniencable** [comment]
Can you disable zeitwerk? I think it isn't compatible with most of the plugins.

**Comment by conveniencable** [comment]
I have fixed this problem at V1.0.15.
