### ISSUE TITLE
Issues are duplicated if the id column is hidden

### ISSUE THREAD

**Issue by otirado-isotrol** [conveniencable/microsoft_project_connector#11]
Hi, we have had a problem with the MS Project plugin, and it is that when we do a Load and hide some columns to reschedule in a more agile way, when we click Save those columns are not updated in redmine. But what really is an issue is that if you hide the id column of the issues, it takes it as 0 and recreates them in redmine.
Regards, and thank you very much.

**Comment by conveniencable** [comment]
Please upgrade to this version:
https://github.com/conveniencable/RedmineConnectorRelease/releases/tag/V1.0.18
