### ISSUE TITLE
Problems entering target version

### ISSUE THREAD

**Issue by sebary302** [conveniencable/microsoft_project_connector#12]
If you select a target version in your search criteria, the LOAD will work fine.
However, when I enter a New Task, the target version is not set.

What should I do?

**Comment by conveniencable** [comment]
Do you mean enter a new task in MS Project and then save it? You need to map the target version to a MS Project:

1. Login to website.
2. Click "Administrator", then click "MS Project Connector".
3. If there is no "Target version" in list, select target version in "New Mapping" dropdown , and then select a Project Column for it, and click Apply finally.
4. In the MS project redmine plugin right sidebar, check the target version mapping, then load or load and merge again. Then you can set the target version when you enter new rows.

**Comment by conveniencable** [comment]
Do you mean enter a new task in MS Project and then save it? You need to map the target version to a MS Project:

1. Login to website.
2. Click "Administrator", then click "MS Project Connector".
3. If there is no "Target version" in list, select target version in "New Mapping" dropdown , and then select a Project Column for it, and click Apply finally.
4. In the MS project redmine plugin right sidebar, check the target version mapping, then load or load and merge again. Then you can set the target version when you enter new rows.

**Comment by conveniencable** [comment]
Do you mean enter a new task in MS Project and then save it? You need to map the target version to a MS Project:

1. Login to website.
2. Click "Administrator", then click "MS Project Connector".
3. If there is no "Target version" in list, select target version in "New Mapping" dropdown , and then select a Project Column for it, and click Apply finally.
4. In the MS project redmine plugin right sidebar, check the target version mapping, then load or load and merge again. Then you can set the target version when you enter new rows.

**Comment by sebary302** [comment]
That was the exact solution.
It was so useful that I purchased a license.

Thank you, Li Chan!
