### ISSUE TITLE
Incorrect Popup UI issues

### ISSUE THREAD

**Issue by sebary302** [conveniencable/microsoft_project_connector#13]
This plugin has helped me so much.
Thank you so much.

One more question: there seems to be a UI error.
As shown in the attached image, the popup is not positioned properly depending on the size of the project window, or there is no background color for the window.
 
![windowsize_popup](https://github.com/conveniencable/microsoft_project_connector/assets/99063578/3719c0be-cb73-4369-881a-79ca85c3a77a)

**Comment by conveniencable** [comment]
If you using Windows 7 or any version less than 10 of Windows, you can resolve it by install Edge browser, else please tell me your Redmine version, Windows version and MS Project version.

**Comment by sebary302** [comment]
> If you using Windows 7 or any version less than 10 of Windows, you can resolve it by install Edge browser, else please tell me your Redmine version, Windows version and MS Project version.

Windows 10
Redmine version                4.2.8.stable
MS Project 2021

Edge browser is installed, of course.

**Comment by conveniencable** [comment]
Please use V1.0.13.

**Comment by sebary302** [comment]
> Please use V1.0.13.

ok. i'll check

**Comment by sebary302** [comment]
![popupui_check](https://github.com/conveniencable/microsoft_project_connector/assets/99063578/f3bfd299-b7a8-4209-8b64-4efa5a1ed548)

Good job, the popup is displayed correctly.
Close the issue.
Thank you!
