### ISSUE TITLE
(IMPORTANT) Incorrect date information by simply saving and loading

### ISSUE THREAD

**Issue by sebary302** [conveniencable/microsoft_project_connector#14]
In PROJECT2021, simply create a New TASK and press the SAVE button to save it...

When I click the LOAD button to import the information from REDMINE, the date information is different.

If you look at the information on the Advanced tab of the TASK information, it may be a hint, so I am attaching an image.

![0_input_task](https://github.com/conveniencable/microsoft_project_connector/assets/99063578/cb102ace-7000-406d-b0a6-41194cb57803)

![1_load_task](https://github.com/conveniencable/microsoft_project_connector/assets/99063578/192809a9-2d85-419e-95ed-4a01e0058d7d)

**Comment by conveniencable** [comment]
The Task Mode is different. It's Manul when you enter the task but Auto when you load the task. The Auto mode skips the weekend.

**Comment by sebary302** [comment]
> The Task Mode is different. It's Manul when you enter the task but Auto when you load the task. The Auto mode skips the weekend.

Task mode is not something I changed.
It was changed to Auto during the Save -> Load process.

If you set the task mode to Auto when you first enter the task and save and load it, the same difference will occur.

**Comment by sebary302** [comment]
This time, I enter a new TestTask2. In Task Auto mode.
Constraint type and Constraint date in the Task Infomation are not what I entered. They were set automatically.

If I save it as it is, it looks like the same information in REDMINE.

However, when I LOAD from PROJECT2021 again, the date is incorrect as I saved it.

![A_input_task](https://github.com/conveniencable/microsoft_project_connector/assets/99063578/a9bd0023-86eb-4d8e-aade-af9d282d63de)


![B_load_task](https://github.com/conveniencable/microsoft_project_connector/assets/99063578/a8ba8978-454a-4267-9fd0-b2e2f3b7b262)

**Comment by conveniencable** [comment]
I will add Constraint Type and Constraint Date to Columns Mapping. Can it solve you problem?

**Comment by sebary302** [comment]
This seems to be possible.
Thanks.

**Comment by conveniencable** [comment]
Please upgrade the MS Project plugin to V1.0.19, and the Redmine Plugin to V1.0.11. As I tested, you must map both Constraint Type and Constraint Date to make the date identical between MS Project and Redmine. 
To map the MS Project enum column like Constraint Type, You must create a list or key/value list type of custom issue field first, and then map it to Ms Project enum column. The Mapping setting page shows the mapping between the custom filed possible values and the MS Project enum values after the mapping added. The Redmine custom filed possible values and the enum values are mapped by index, so you can use your own language, and change the custom fields's possible values to fit it.

**Comment by sebary302** [comment]
Thanks, I'll test that feature!
I will gladly be a tester for this plugin!
