### ISSUE TITLE
Notes Load/Save issue

### ISSUE THREAD

**Issue by sebary302** [conveniencable/microsoft_project_connector#15]
Notes saves values on save regardless of whether it is checked or unchecked when loading in the project (this is caused by the unconditional saving of Notes to Redmine).
So if you uncheck Notes and load and save, all the notes in Redmine will be deleted.

**Comment by sebary302** [comment]
The new version of the plugin preserves the checkbox status of the note, even if there are no comments.

However, the note is updated even if the checkbox is unchecked.
Other items should behave the same way, updating only when the checkbox is checked.

**Comment by conveniencable** [comment]
I think you have to reload it before save to redmine if the plugin version >= V1.0.20.

**Comment by sebary302** [comment]
My test case is wrong.
In previous versions, it was clear that the notes would be updated regardless of the state of the checkbox.

After the version you mentioned, only the selected data is saved on load. 
But my test case tested what happens if the item selected on LOAD is unchecked before SAVE.

If this is the specification you are referring to, I have confirmed that it works now.

**Comment by conveniencable** [comment]
The saving funtion use the mapped fields it loaded, so the checked fileds are only effect on Load/Load and Merge, but not on Save.
The previous versions only save the visible MS Project columns while I didn't know how to store custom data, which is unreasonable.

**Comment by sebary302** [comment]
Understood.
