### ISSUE TITLE
[IMPORTANT] Start date Finish date time format problem

### ISSUE THREAD

**Issue by sebary302** [conveniencable/microsoft_project_connector#17]
When you Load in Project 2021, the Finish time is entered with the time information removed as shown in the image.
(The % image is a VBA script that took the date value as debug information; it is the correct value).

This causes the end of the task time to be centered at 00:00:00 on that date, which is incorrect for the actual schedule information.
Presumably the Start value is loaded the same way, but I think the time value is set as it is entered as the Finish criteria and the date adjustment happens automatically.

It seems that the time information should also be entered when loading based on the daylight hours set in Project 2021 on that date so that the date error does not occur.

![date and time issue_](https://github.com/conveniencable/microsoft_project_connector/assets/99063578/36920e38-c6ab-4c41-bad7-39293a03e534)

oSubTask.Finish = immediately after loading from the plugin (no time value).
oSubTask.Finish2 = when the date is manually selected as normal.

**Comment by conveniencable** [comment]
But the redmine only suport Date and there is no Datetime fields in it.

**Comment by sebary302** [comment]
That's right. I took a look and it was.
So I thought about it.

The solution is to combine the date value with ActiveProject.defaultStartTime and ActiveProject.defaultFinishTime when loading from the project plugin to provide the time values for the Start and Finish columns.

This should work in almost all cases without exception.

**Comment by sebary302** [comment]
> But the redmine only suport Date and there is no Datetime fields in it.

That's right. I took a look and it was.
So I thought about it.

The solution is to combine the date value with ActiveProject.defaultStartTime and ActiveProject.defaultFinishTime when loading from the project plugin to provide the time values for the Start and Finish columns.

This should work in almost all cases without exception.

**Comment by conveniencable** [comment]
Please upgrade MS Project  plugin to this version: https://github.com/conveniencable/RedmineConnectorRelease/releases/tag/V1.0.21

And then check "Use Default Start & Finish Time" in the setting dialog.

**Comment by sebary302** [comment]
> Please upgrade MS Project plugin to this version: https://github.com/conveniencable/RedmineConnectorRelease/releases/tag/V1.0.21
> 
> And then check "Use Default Start & Finish Time" in the setting dialog.

good news! I'll test it!

**Comment by sebary302** [comment]
I verified that the function works fine.
Great work!
