### ISSUE TITLE
Cannot multiselect in the Load condition.

### ISSUE THREAD

**Issue by sebary302** [conveniencable/microsoft_project_connector#18]
In Redmine, you can multiselect by pressing the + button on the "equal to" condition in the search criteria. (shift key or ctrl key + click)

The plugin's UI follows the same format.
However, it doesn't allow multiple selections.

![multiselct](https://github.com/conveniencable/microsoft_project_connector/assets/99063578/de55fc25-2d46-470b-84f3-b255df52ead4)

**Comment by conveniencable** [comment]
Please upgrade the redmine plugin to 1.0.12.

**Comment by sebary302** [comment]
> Please upgrade the redmine plugin to 1.0.12.

This still doesn't allow for multiselect.
For example, there is no way to select target versions A and B at the same time.

**Comment by conveniencable** [comment]
There is a plug sign when you choose is operator, like this:
![图片](https://github.com/conveniencable/microsoft_project_connector/assets/72964320/b0735690-c18d-4d91-834d-d861204b46d9)

**Comment by sebary302** [comment]
> There is a plug sign when you choose is operator, like this: ![图片](https://user-images.githubusercontent.com/72964320/250463463-b0735690-c18d-4d91-834d-d861204b46d9.png)

Looking at your screen, it seems to be working.
For some reason it doesn't work for me... :(
Pressing the + button doesn't change anything.

What should I check?

- 
Windows 10
Redmine version 4.2.8.stable
MS Project 2021 (with plugin 1.0.21.0)
-

**Comment by conveniencable** [comment]
Please use V1.0.13.

**Comment by sebary302** [comment]
> Please use V1.0.13.

ok. i'll check

**Comment by sebary302** [comment]
![multiselect_check](https://github.com/conveniencable/microsoft_project_connector/assets/99063578/f7a22b31-2617-459f-83b9-916ef6eb86b8)

Good job, it works!
Close the issue.

Thank you!
