### ISSUE TITLE
Events from the plug-in that can be used in VBA scripts

### ISSUE THREAD

**Issue by sebary302** [conveniencable/microsoft_project_connector#19]
I use this Redmine plugin and a VBA script in my project to facilitate various tasks.

I am using VBA to receive and process multiple events.

I would like to know if there is a way to receive the status of the Redmine plugin and certain events in VBA.

For example 
. Load button pressed / Load started / Load in progress / Load completed
. Save button pressed/Save started/Save in progress/Save completed.
. When added to LOAD as a unit of task

**Comment by conveniencable** [comment]
I don't know how to communicate with VBA. But for Load, you can detect the task change even, it loads or changes the tasks one by one, so the change events are trigered one by one. So you have to use the "rebound" strategy: wait like 2 seconds to execute actual VBA progress in every event, if the next even comes in 2 seconds, just cancel and start the waiting again, after sequences of waiting and canceling, the final even always there when there is no after even to interrupt and the acrual VBA progress can be executed finally.

**Comment by sebary302** [comment]
It's simple and a good idea. Thank you. I'll give it a try.
