### ISSUE TITLE
no render webview2 into msproject

### ISSUE THREAD

**Issue by derevyov** [conveniencable/microsoft_project_connector#2]
hi. i'm installed plugin and connector;
after click 'open' in msProject I see grey square and test "webView2"
windows 10 LTSС 2016
msProject 2013
<a href="https://fastpic.org/view/115/2021/0930/76023eda4a080ed6829383eda85915b4.png.html" target="_blank"><img src="https://i115.fastpic.org/thumb/2021/0930/b4/76023eda4a080ed6829383eda85915b4.jpeg" border="0"></a>

**Comment by conveniencable** [comment]
Just reinstall it with a computer being online.

Or download the webveiw2 runtime and install it menual:
https://developer.microsoft.com/en-us/microsoft-edge/webview2/

**Comment by conveniencable** [comment]
Please download the VSTO runtime and install:
https://download.visualstudio.microsoft.com/download/pr/1f5af042-d0e4-4002-9c59-9ba66bcf15f6/089f837de42708daacaae7c04b7494db/ndp472-kb4054530-x86-x64-allos-enu.exe
