### ISSUE TITLE
Losing parent-child hierarchy when using LOAD filters

### ISSUE THREAD

**Issue by sebary302** [conveniencable/microsoft_project_connector#20]
Your help has made it so much easier for me and I'm enjoying all the great features. Thank you.

Now that I've gained some usability, I'm trying to manage some bigger tasks this time.
In doing so, I found a new problem.

If you use a filter when loading a task and modify and save the task without the parent hierarchy task loaded, the task will lose the parent hierarchy task based on the on-load condition.

For example)

A parent hierarchy task named A is assigned to "MIKE"
A child hierarchy task named B is assigned to "DAVE".

In this case, if you filter for the assignee "DAVE" on LOAD, then only the B task will be loaded.

If you modify and save the progress of the job as it is, job B is no longer a child of job A.

So I always have to load and work on all the jobs without filtering (which is a lot of work).

------
The expected behavior is as follows

The parent hierarchy task of the task being loaded should be loaded, as well as all related tasks.

**Comment by conveniencable** [comment]
Please update the redmine plugin to the late version(V1.0.14).
