### ISSUE TITLE
Error loading

### ISSUE THREAD

**Issue by otirado-isotrol** [conveniencable/microsoft_project_connector#23]
Hi, we are using connector version 1.0.18 for several colleagues in the company and it works correctly for all of us, except for one colleague who, when loading any project from an empty project sheet, gets the following error:
![error_load](https://github.com/conveniencable/microsoft_project_connector/assets/133744123/34a2a4cb-20ac-4a57-8702-edf3ae69e79c)
I have checked the redmine logs and everything seems to be correct, so it seems to be a connector problem.

It should be noted that other colleagues have tried to load the same project and it has worked for them.

_One important thing, we would like to continue maintaining version 1.0.18 without having to update to 1.0.21 which produces changes to the redmine plugin code._

Regards, and thank you very much.

**Comment by conveniencable** [comment]
It's the date format problem, please change the language in Redmine(just for his account) or the date format in the Excel in his computer to make the date format match.

**Comment by otirado-isotrol** [comment]
Perfect, it's already fixed.

Thank you so much.
