### ISSUE TITLE
"Load" Issue.

### ISSUE THREAD

**Issue by descalona2023** [conveniencable/microsoft_project_connector#29]
When I try to align the information from redmine to MS Project by clicking on "load" I get the following error:

System.FormatException: Cannot recognize string as valid DateTime value. en System.DateTimeParse.Parse(String s, DateTimeFormatInfo dtfi, DateTimeStyles styles) en NZWlJ1CpgZS1P1mL8N.KGWDAn8g69rVrNPiCT.<>c__DisplayClass10_0.RYIN1TfEMQqeR9odscL(Object ) en NZWlJ1CpgZS1P1mL8N.KGWDAn8g69rVrNPiCT.<>c__DisplayClass10_0.b__10(IssueData issue) in NZWlJ1CpgZS1P1mL8N.KGWDAn8g69rVrNPiCT.v4Cd6NIW94eDnabifHd(Object , Object ) in NZWlJ1CpgZS1P1mL8N.KGWDAn8g69rVrNPiCT.O4RLxQ5DV(Task , IssueData ) in LLxRP2xauCrpLYgBJ8W.CELXZKxBtq4BTsp3HP4.gaEZoYUnlu(Object , Object , Int16 , Dictionary`2 , Dictionary`2 ) in LLxRP2xauCrpLYgBJ8W.CELXZKxBtq4BTsp3HP4.Rc3Zyhsf2R(Object , Object ) in RedmineConnector.ScriptObject.xpOmdFiEJjDCPvqWPCb(Object , Object ) in RedmineConnector.ScriptObject.loadIssues(String jsonString, Boolean isMerge)
![Annotation 2024-01-12 105052](https://github.com/conveniencable/microsoft_project_connector/assets/154468939/738fd919-d6ae-47c1-b67e-c29d9e6c8f68)

Because of it is impossible for me to transfer the information correctly, how can I make this not happen?

**Comment by conveniencable** [comment]
It's about the date formate in redmine, you can change your language in redmine to make the date format accomodate to you PC.
