### ISSUE TITLE
How to mapping the issues relationship(Predecessors) in this plugin?

### ISSUE THREAD

**Issue by uart-aplex** [conveniencable/microsoft_project_connector#3]
There are many issues relationships in project, if cannot load them automatically then will need to spend a lot of time to re-create them in MS project. I didn't fine a way to use it.

![Snap2](https://user-images.githubusercontent.com/24597310/136131782-072bb3d6-6478-47f8-87db-9fa4ae215844.jpg)

**Comment by conveniencable** [comment]
The redmine issue relation types are not compliance with MS Project's dependency types except "follow/procedes" which is similar to "FS". So only the 4 MS Project dependency types(SS, SF, FF, FS) can be maintained in MS Project. The 4 MS Project dependency types are added as addition issue relation types to redmine and can be maintained in Redmine side, too.
