### ISSUE TITLE
Delivery of licence key? 

### ISSUE THREAD

**Issue by sjanjac** [conveniencable/microsoft_project_connector#30]
I tested the plugin and it works fine.
I ordered the full version but the license key was not delivered.
I have not received the requested key even after specifically contacting conveniencecable@outlook.com.
Why don't they deliver?
SJ

**Comment by conveniencable** [comment]
If the system has no problem, the license key should have sent to the email of the paypal account which was used to paied for it.
If you couldn't find it in your  paypal email, please provide an email, I will sent it manually.

**Comment by sjanjac** [comment]
Hello,

I used following ***@***.*** during purchasing process on your site:
***@***.***
but you can use my direct mail:
***@***.***

My Paypal mail is another one (gmail).
I didn't got the key on any of these addresses.
Please resend me the key or even better you can refund the amount on my Paypal account.
I still opened claiming process on Paypal.

BR


Stanislav Janjac | CEO

M: +385 99 358 5 358

E: ***@***.******@***.***> | www.commondo.eu<http://www.commondo.eu>

________________________________
