### ISSUE TITLE
Error while merging or saving changes to redmine

### ISSUE THREAD

**Issue by RAPGabs** [conveniencable/microsoft_project_connector#31]
While loading or saving my mpp to redmine I am getting the following errors
`System.Runtime.InteropServices.COMException (0x800A044D): This is not a valid lookup table value. at Microsoft.Office.Interop.MSProject.Task.SetField(PjField FieldID, String Value) at NZWlJ1CpgZS1P1mL8N.KGWDAn8g69rVrNPiCT.O4RLxQ5DV(Task , IssueData ) at LLxRP2xauCrpLYgBJ8W.CELXZKxBtq4BTsp3HP4.gaEZoYUnlu(Object , Object , Int16 , Dictionary`2 , Dictionary`2 ) at LLxRP2xauCrpLYgBJ8W.CELXZKxBtq4BTsp3HP4.gaEZoYUnlu(Object , Object , Int16 , Dictionary`2 , Dictionary`2 ) at LLxRP2xauCrpLYgBJ8W.CELXZKxBtq4BTsp3HP4.Rc3Zyhsf2R(Object , Object ) at RedmineConnector.ScriptObject.xpOmdFiEJjDCPvqWPCb(Object , Object ) at RedmineConnector.ScriptObject.loadIssues(String jsonString, Boolean isMerge)`

![image](https://github.com/conveniencable/microsoft_project_connector/assets/96489092/a63758af-a371-49d9-a70c-62753691a5aa)

**Comment by conveniencable** [comment]
What's the version of MS Project? Can you take a screenshot to show the selected Redmine fields loading to MS Project?

**Comment by RAPGabs** [comment]
Hey Li,

I am using v2406.
![image](https://github.com/conveniencable/microsoft_project_connector/assets/96489092/583074e0-ca7a-4c5b-bcb1-e7eae167f73f)

The following columns are being loaded in MSP.
![image](https://github.com/conveniencable/microsoft_project_connector/assets/96489092/6e8c5c48-624f-42e6-8fec-5b3f64fc0be3)

**Note:** If I uncheck "Target version" and then load/save everything works as intended. There is no error. But having it checked causes the error above. Target version being a mandatory field I cannot make tasks in Redmine.

**Comment by conveniencable** [comment]
Does the Text5 field has folumar validation?

**Comment by RAPGabs** [comment]
Yes, it is a mandatory field to make tasks. We have a dropdown; the same way we have dropdowns for "Status" or "Tracker".

![image](https://github.com/user-attachments/assets/b9ebd458-88d1-4bef-a79d-9d023c277e79)

**Comment by conveniencable** [comment]
What's you redmine version? 
This circumstance looks like some Redmine issues's using a missing target versoin which is not in the dropdown, but I don't know how to make it as the used target version couldn't be deleted. Could you try to use the NOT filter selecting all the availables target version to see if it can find some exception issues.

**Comment by RAPGabs** [comment]
Redmine version is 4.2 stable.

While filtering out tasks with no target version, i just get change requests.

Another observation: Even though I get errors when loading tasks with target version checked, I get target versions of other projects in the drop-down, sometimes even for those projects that I have access to. 

Very weird.

**Comment by conveniencable** [comment]
> Redmine version is 4.2 stable.
> 
> While filtering out tasks with no target version, i just get change requests.
> 
> Another observation: Even though I get errors when loading tasks with target version checked, I get target versions of other projects in the drop-down, sometimes even for those projects that I have access to.
> 
> Very weird.

I think the these issues with exception target version were created in another project, and then changed to this project later.
So the solution is: change these issues to invalid target versions, it's quite easy by bulk operation in Redmine.

**Comment by RAPGabs** [comment]
Understood, I will check it out and revert back with my findings.

**Comment by RAPGabs** [comment]
> I think the these issues with exception target version were created in another project, and then changed to this project later. So the solution is: change these issues to invalid target versions, it's quite easy by bulk operation in Redmine.

I cloned the actual Redmine and set up a local version to try what you suggested with moving tickets from one project to another project that didn't have an error while synchronising. But couldn't replicate this.

The cause of the error is something different.

Even on the same Redmine setup with multiple projects, only some projects have this issue, while others don't.

**Comment by conveniencable** [comment]
> > I think the these issues with exception target version were created in another project, and then changed to this project later. So the solution is: change these issues to invalid target versions, it's quite easy by bulk operation in Redmine.
> 
> I cloned the actual Redmine and set up a local version to try what you suggested with moving tickets from one project to another project that didn't have an error while synchronising. But couldn't replicate this.
> 
> The cause of the error is something different.
> 
> Even on the same Redmine setup with multiple projects, only some projects have this issue, while others don't.

The current latest version of MS Project plugin doesn't raised this error anymore: https://github.com/conveniencable/RedmineConnectorRelease/releases/tag/V1.0.23. But it fill the cell with empty because it's a dirty value in dropdown.

It's clear that this exception "System.Runtime.InteropServices.COMException (0x800A044D)" is caused by setting a value not in the dropdown.  I don't know how to make a dirty target version value in a issue, but from the diff between 4.2 stable and 5.1 stable in redmine source code: https://github.com/redmine/redmine/compare/4.2-stable...5.1-stable, you can see the method update_versions in issue.rb had been improved by adding retry to update every issue's target version to empty  when the current target version is not in dropdown in the current project. So I guess there is a little chance that an issue may keep dirty target version when a target version's sharing is changed and then it's not available for the issues's project. 

Below show how to change the sharing of the target version:
![图片](https://github.com/user-attachments/assets/c29d7989-f606-4cc5-b6b4-41cbc7441db2)
