### ISSUE TITLE
"is_changed" not change in related issues

### ISSUE THREAD

**Issue by otirado-isotrol** [conveniencable/microsoft_project_connector#6]
Hi, I have a problem with the plugin and it is that when I have a parent issue and another child issue, and I modify, for example, the start date of the child, the parent issue's date also changes because it depends on it, but the "is_changed" field of the parent issue does not change, so it does not update me when I synchronize in redmine.

I show you with screenshots:

When I press Load

![before](https://github.com/conveniencable/microsoft_project_connector/assets/133744123/9f309233-0586-4931-96ae-330d008962d8)

After changing the start date

![not_changed](https://github.com/conveniencable/microsoft_project_connector/assets/133744123/038bbb32-bf38-4a42-8c87-29a0836f0b16)

"is_changed" of the parent task has not changed but its start date has.

This is an example, but it happens whenever a task changes something because some related task has been changed.

Regards, and thank you very much.

**Comment by conveniencable** [comment]
In the old computer, the VSTO has a bug that it won't trigger change even on the other related tasks.

Please upgrade to the last versions: MS Project plugin  V1.0.13, Redmine plugin  V1.0.9. At the MS Project Plugin, Please Click "Setting", and then check "Save Changed Related Tasks" and save.

**Comment by otirado-isotrol** [comment]
hi,
I have tried changing the start date and the end date and it works, it has detected the field, but when I try to 'set baseline' it does not detect the change.
I'll explain the steps I follow, sorry because the screenshots are in Spanish:

I have the following mapping between baselines fields and redmine fields
![mapeo](https://github.com/conveniencable/microsoft_project_connector/assets/133744123/c13decef-f524-45f3-8934-e32238487777)
When I click 'Load' get:
![load(1)](https://github.com/conveniencable/microsoft_project_connector/assets/133744123/a8cc62b9-72b6-48f1-b93d-01874b7a8331)
Then I set baseline in MS project for it I click on Project-Set Baseline-Set Baseline
![set_baseline](https://github.com/conveniencable/microsoft_project_connector/assets/133744123/78d06f86-37bc-4e42-a3b4-cb57136bfce7)

And click 'OK', baselines are established but "is_changed" has not detected it

![not_change_baselines](https://github.com/conveniencable/microsoft_project_connector/assets/133744123/13d1033c-3a04-48e7-9b45-1b9009fa4355)

Regards, and thank you very much.

**Comment by conveniencable** [comment]
The is_changed problem on Baseline is fixed. Please update the MS Project plugin to V1.0.14.  Please also upgrade to the last redmine plugin which fixed 2 issues.

**Comment by otirado-isotrol** [comment]
Thank you very much, everything works correctly.
