### ISSUE TITLE
Notes field does not sync to redmine

### ISSUE THREAD

**Issue by otirado-isotrol** [conveniencable/microsoft_project_connector#7]
I have mapped the ms project notes field with the redmine description field. When loading the tasks in ms project if it shows me correctly the description in the notes field. But if I change the notes field or add to a task that did not have the notes field and I click "Save" I do not add/update it in redmine.

In redmine:
![test 1](https://github.com/conveniencable/microsoft_project_connector/assets/133744123/3fbb9f37-9306-471a-98db-b391e4f2ef1a)

When "Load" in MS Project
![desc](https://github.com/conveniencable/microsoft_project_connector/assets/133744123/d9dba0a5-79d9-4f79-9f08-3ed6cd5e45a8)

Add "Notes" in TEST 2
![add_des](https://github.com/conveniencable/microsoft_project_connector/assets/133744123/67dac320-657a-47d6-afb5-d559c33d6483)

After click "Save"

![test2](https://github.com/conveniencable/microsoft_project_connector/assets/133744123/a0913c47-e084-442c-9ec2-f0853a82221e)

Regards, and thank you very much.

**Comment by conveniencable** [comment]
Please upgrade to the last versions: MS Project plugin  V1.0.13, Redmine plugin  V1.0.9.

**Comment by otirado-isotrol** [comment]
Great, it works fine now. Thank you so much
