### ISSUE TITLE
Does not escape special characters in notes field

### ISSUE THREAD

**Issue by otirado-isotrol** [conveniencable/microsoft_project_connector#8]
Hi, using the new version of the plugin an error occurs when we have mapped the Notes field of MS Project with the Description field of redmine. This error occurs when the text contains special characters such as spaces or double quotes ("), I don't know if there is another. 
![des](https://github.com/conveniencable/microsoft_project_connector/assets/133744123/04c97021-1676-4e45-b4a8-b2c4bc79726a)

And it is that when we click "Save" in redmine an error occurs in the line of code in which it is done: issues_hash = JSON.parse params[:data] logging the message: **JSON::ParserError (434: unexpected token at '{"line_no":"1"**...

Please, see if this error can be corrected and also check that it does not occur in another text-type field such as the theme or any custom text-type field.

Regards, and thank you very much.

**Comment by conveniencable** [comment]
Fixed in late MS Project plugin V1.0.15

**Comment by otirado-isotrol** [comment]
Thank you very much, everything works correctly.
