### ISSUE TITLE
Not render plugin in MS Project

### ISSUE THREAD

**Issue by otirado-isotrol** [conveniencable/microsoft_project_connector#9]
Hi, a coworker has installed the latest version of the ms project plugin. And when he hits "Open" the redmine part is grayed out.
![not_found](https://github.com/conveniencable/microsoft_project_connector/assets/133744123/1d4ec607-c7a6-4da2-8e3d-8035a1747f5d)
We have tried uninstalling and reinstalling the plugin, but still the same and going back to an old version of the plugin.
We have also followed what you put in https://github.com/conveniencable/microsoft_project_connector/issues/2 but we have the latest version of webview2 runtime.
We don't know what else to do or try, I leave you the version of ms project that you have installed on Windows 10
![version](https://github.com/conveniencable/microsoft_project_connector/assets/133744123/37f2bf7e-b51d-47e6-a03d-04e22c5c4008)
Regards, and thank you very much.

**Comment by conveniencable** [comment]
I think it's because I upgrade to the new .net framework. I just added 2 old dotnet packages here:
https://github.com/conveniencable/RedmineExcelConnectorRelease/releases/tag/V1.0.0.8
Please try it.

**Comment by otirado-isotrol** [comment]
I have downloaded RedmineExcelConnector_x64-1.0.0.8_old_dotnet.exe I have executed it, but it continues the same.

**Comment by conveniencable** [comment]
Sorry, sent a wrong package for Excel before, here is the new one:
https://github.com/conveniencable/RedmineConnectorRelease/releases/tag/V1.0.16

**Comment by otirado-isotrol** [comment]
We have installed redmine_connector_x64_1.0.16.exe on two Windows 10 computers and the plugin has been inactivated and cannot be activated.
![actives](https://github.com/conveniencable/microsoft_project_connector/assets/133744123/6ae6e804-4dae-41b2-bda4-fa4836687724)

Nor does it let us go back to a previous version, that is, I uninstall v 1.0.16 and install 1.0.15 and it appears the same.

**Comment by conveniencable** [comment]
Please reinstall this version:
https://github.com/conveniencable/RedmineConnectorRelease/releases/tag/V1.0.17

Or just install the VSTO runtime manually:
https://download.visualstudio.microsoft.com/download/pr/1f5af042-d0e4-4002-9c59-9ba66bcf15f6/089f837de42708daacaae7c04b7494db/ndp472-kb4054530-x86-x64-allos-enu.exe

**Comment by otirado-isotrol** [comment]
Thank you very much, seems to have been fixed. Just one detail, you can enable Spanish in the plugin, currently it comes out in Chinese.
![not_spanish](https://github.com/conveniencable/microsoft_project_connector/assets/133744123/8c7b62f7-d5c9-4dc1-90ba-1b06ca38bd2b)

**Comment by conveniencable** [comment]
You can change the user's language in redmine: 

1. login to redmine website.
2. click "My Account" in top left.
3. change the language and save.

**Comment by otirado-isotrol** [comment]
Thank you very much, seems to have been fixed.
